services:
  - type: web
    name: google-maps-scraper
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
    build:
      packages:
        - chromium
        - chromium-browser
        - chromium-driver
        - fonts-liberation
        - libappindicator3-1
        - libasound2
        - libatk-bridge2.0-0
        - libatk1.0-0
        - libcups2
        - libdbus-1-3
        - libgdk-pixbuf2.0-0
        - libnspr4
        - libnss3
        - libxss1
        - lsb-release
        - xdg-utils
